import { quoteIdent } from './sqlShared.js'

/**
 * Minimal query surface shared by `pg`'s Pool and PoolClient. The capture MUST
 * run on a single client (not the pool) because it pins `search_path` for the
 * session — see `capturePostgresDdl`.
 */
export interface PgQueryRunner {
  query: (text: string, values?: unknown[]) => Promise<{ rows: Array<Record<string, unknown>> }>
}

const quoteLiteral = (value: string) => `'${value.replace(/'/g, "''")}'`

/**
 * Extension statements are the one part of the capture that may legitimately
 * fail on the target: managed production databases carry provider extensions
 * (e.g. Neon's `neon`) that a local Postgres has no binaries for. The restore
 * detects them with this prefix and soft-fails them inside a savepoint — if
 * schema objects genuinely need the extension, the CREATE TABLE that follows
 * still fails loudly.
 */
export const EXTENSION_DDL_PREFIX = 'CREATE EXTENSION IF NOT EXISTS '

interface ColumnRow {
  column_name: string
  data_type: string
  default_expr: null | string
  generated: string
  identity: string
  not_null: boolean
  table_name: string
}

const renderColumn = (column: ColumnRow): string => {
  let ddl = `${quoteIdent(column.column_name)} ${column.data_type}`
  // A generated column's pg_attrdef entry holds the generation expression, not
  // a default — emitting it as DEFAULT would silently corrupt the table.
  if (column.generated === 's') {
    ddl += ` GENERATED ALWAYS AS (${column.default_expr}) STORED`
  } else if (column.identity === 'a') {
    ddl += ' GENERATED ALWAYS AS IDENTITY'
  } else if (column.identity === 'd') {
    ddl += ' GENERATED BY DEFAULT AS IDENTITY'
  } else if (column.default_expr) {
    ddl += ` DEFAULT ${column.default_expr}`
  }
  if (column.not_null) {
    ddl += ' NOT NULL'
  }
  return ddl
}

/**
 * Reconstructs the DDL of every user object in a Postgres schema — the pg_dump
 * equivalent of the SQLite path's `sqlite_master` capture, built from the
 * system catalogs so no external binary is needed. Payload/Drizzle-generated
 * schemas are a constrained subset of Postgres (plain tables, enums, serial or
 * identity ids, btree indexes, FK/PK/unique constraints), all of which the
 * catalogs can decompile for us via `pg_get_constraintdef`/`pg_get_indexdef`.
 *
 * The session's `search_path` is pinned to `schemaName` for the duration so the
 * decompiler functions (`format_type`, `pg_get_expr`, `pg_get_constraintdef`,
 * pretty `pg_get_indexdef`) emit UNQUALIFIED identifiers for objects in that
 * schema. The restore replays the statements with `search_path` pinned to the
 * TARGET schema, so the capture stays valid even if the two schema names differ.
 *
 * Statement order: extensions → enums → sequences → tables → sequence
 * ownership → constraints (PK/unique before FK) → remaining indexes.
 */
export const capturePostgresDdl = async (
  client: PgQueryRunner,
  schemaName: string,
): Promise<string[]> => {
  await client.query(`SET search_path TO ${quoteIdent(schemaName)}`)
  try {
    return await captureWithSearchPath(client, schemaName)
  } finally {
    // The client goes back to a pool the live adapter keeps using — restore its
    // role/database default search_path so the pin doesn't leak.
    await client.query('SET search_path TO DEFAULT')
  }
}

/**
 * SQL fragment excluding objects owned by an extension (deptype 'e'): those are
 * created by the replayed CREATE EXTENSION — with their own seed data — so
 * capturing their DDL (or their rows, see listBaseTables) would collide on
 * restore. `alias` is the pg_class/pg_type alias of the candidate object.
 */
const notExtensionMember = (classCatalog: 'pg_class' | 'pg_type', alias: string) =>
  `NOT EXISTS (
     SELECT 1 FROM pg_depend ext_dep
     WHERE ext_dep.classid = '${classCatalog}'::regclass AND ext_dep.objid = ${alias}.oid
       AND ext_dep.refclassid = 'pg_extension'::regclass AND ext_dep.deptype = 'e'
   )`

const captureWithSearchPath = async (
  client: PgQueryRunner,
  schemaName: string,
): Promise<string[]> => {
  const statements: string[] = []

  // Extensions (e.g. postgis for point fields). Replayed with IF NOT EXISTS:
  // on the target they may survive the schema wipe when installed elsewhere.
  const extensions = await client.query(
    `SELECT extname FROM pg_extension WHERE extname <> 'plpgsql' ORDER BY extname`,
  )
  for (const row of extensions.rows) {
    statements.push(`${EXTENSION_DDL_PREFIX}${quoteIdent(String(row.extname))}`)
  }

  // Enums, with labels in their defined order.
  const enums = await client.query(
    `SELECT t.typname AS name, e.enumlabel AS label
     FROM pg_type t
     JOIN pg_namespace n ON n.oid = t.typnamespace
     JOIN pg_enum e ON e.enumtypid = t.oid
     WHERE n.nspname = $1 AND ${notExtensionMember('pg_type', 't')}
     ORDER BY t.typname, e.enumsortorder`,
    [schemaName],
  )
  const labelsByEnum = new Map<string, string[]>()
  for (const row of enums.rows) {
    const name = String(row.name)
    const labels = labelsByEnum.get(name) ?? []
    labels.push(String(row.label))
    labelsByEnum.set(name, labels)
  }
  for (const [name, labels] of labelsByEnum) {
    statements.push(
      `CREATE TYPE ${quoteIdent(name)} AS ENUM (${labels.map(quoteLiteral).join(', ')})`,
    )
  }

  // Standalone and serial-owned sequences. Identity-owned sequences (internal
  // dependency, deptype 'i') are excluded: the column's GENERATED ... AS
  // IDENTITY clause recreates those implicitly.
  const sequences = await client.query(
    `SELECT s.relname AS name, format_type(seq.seqtypid, NULL) AS data_type,
            seq.seqincrement AS increment, seq.seqmin AS min_value,
            seq.seqmax AS max_value, seq.seqstart AS start_value,
            seq.seqcache AS cache_size, seq.seqcycle AS cycle
     FROM pg_class s
     JOIN pg_namespace n ON n.oid = s.relnamespace
     JOIN pg_sequence seq ON seq.seqrelid = s.oid
     WHERE n.nspname = $1
       AND NOT EXISTS (
         SELECT 1 FROM pg_depend d
         WHERE d.classid = 'pg_class'::regclass AND d.objid = s.oid AND d.deptype = 'i'
       )
       AND ${notExtensionMember('pg_class', 's')}
     ORDER BY s.relname`,
    [schemaName],
  )
  for (const row of sequences.rows) {
    statements.push(
      `CREATE SEQUENCE ${quoteIdent(String(row.name))} AS ${String(row.data_type)}` +
        ` INCREMENT BY ${String(row.increment)} MINVALUE ${String(row.min_value)}` +
        ` MAXVALUE ${String(row.max_value)} START WITH ${String(row.start_value)}` +
        ` CACHE ${String(row.cache_size)}${row.cycle ? ' CYCLE' : ''}`,
    )
  }

  // Tables with their columns, in original column order.
  const columns = await client.query(
    `SELECT c.relname AS table_name, a.attname AS column_name,
            format_type(a.atttypid, a.atttypmod) AS data_type,
            a.attnotnull AS not_null, a.attidentity AS identity,
            a.attgenerated AS generated,
            pg_get_expr(d.adbin, d.adrelid) AS default_expr
     FROM pg_class c
     JOIN pg_namespace n ON n.oid = c.relnamespace
     JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum > 0 AND NOT a.attisdropped
     LEFT JOIN pg_attrdef d ON d.adrelid = c.oid AND d.adnum = a.attnum
     WHERE n.nspname = $1 AND c.relkind = 'r' AND ${notExtensionMember('pg_class', 'c')}
     ORDER BY c.relname, a.attnum`,
    [schemaName],
  )
  const columnsByTable = new Map<string, ColumnRow[]>()
  for (const row of columns.rows) {
    const table = String(row.table_name)
    const list = columnsByTable.get(table) ?? []
    list.push(row as unknown as ColumnRow)
    columnsByTable.set(table, list)
  }
  for (const [table, tableColumns] of columnsByTable) {
    statements.push(
      `CREATE TABLE ${quoteIdent(table)} (\n  ${tableColumns.map(renderColumn).join(',\n  ')}\n)`,
    )
  }

  // Serial-style sequence ownership (deptype 'a'), so pg_get_serial_sequence —
  // and therefore the post-restore sequence advance — keeps working.
  const ownerships = await client.query(
    `SELECT s.relname AS seq_name, t.relname AS table_name, a.attname AS column_name
     FROM pg_depend d
     JOIN pg_class s ON s.oid = d.objid AND s.relkind = 'S'
     JOIN pg_namespace n ON n.oid = s.relnamespace
     JOIN pg_class t ON t.oid = d.refobjid
     JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = d.refobjsubid
     WHERE d.classid = 'pg_class'::regclass AND d.refclassid = 'pg_class'::regclass
       AND d.deptype = 'a' AND n.nspname = $1 AND ${notExtensionMember('pg_class', 's')}
     ORDER BY s.relname`,
    [schemaName],
  )
  for (const row of ownerships.rows) {
    statements.push(
      `ALTER SEQUENCE ${quoteIdent(String(row.seq_name))} OWNED BY ` +
        `${quoteIdent(String(row.table_name))}.${quoteIdent(String(row.column_name))}`,
    )
  }

  // Constraints, decompiled by the server. PK/unique first so FKs can target
  // them; all tables already exist by this point.
  const constraints = await client.query(
    `SELECT c.relname AS table_name, con.conname AS name,
            pg_get_constraintdef(con.oid) AS definition
     FROM pg_constraint con
     JOIN pg_class c ON c.oid = con.conrelid
     JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = $1 AND con.contype IN ('p', 'u', 'c', 'x', 'f')
       AND ${notExtensionMember('pg_class', 'c')}
     ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'c' THEN 2
                               WHEN 'x' THEN 3 ELSE 4 END,
              c.relname, con.conname`,
    [schemaName],
  )
  for (const row of constraints.rows) {
    statements.push(
      `ALTER TABLE ${quoteIdent(String(row.table_name))} ADD CONSTRAINT ` +
        `${quoteIdent(String(row.name))} ${String(row.definition)}`,
    )
  }

  // Remaining indexes — those NOT backing a constraint (constraint indexes were
  // recreated implicitly above). The pretty pg_get_indexdef variant is used
  // because only it honors search_path when naming the table; the plain variant
  // always schema-qualifies, which would pin the DDL to the source schema name.
  const indexes = await client.query(
    `SELECT pg_get_indexdef(i.indexrelid, 0, true) AS definition, ic.relname AS name
     FROM pg_index i
     JOIN pg_class ic ON ic.oid = i.indexrelid
     JOIN pg_class tc ON tc.oid = i.indrelid
     JOIN pg_namespace n ON n.oid = tc.relnamespace
     WHERE n.nspname = $1 AND tc.relkind = 'r'
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = i.indexrelid)
       AND ${notExtensionMember('pg_class', 'tc')}
     ORDER BY ic.relname`,
    [schemaName],
  )
  for (const row of indexes.rows) {
    statements.push(String(row.definition))
  }

  return statements
}
